table 'Databel - Data'
	lineageTag: f5d08f5f-30e7-429a-bd29-020c68ff2079

	measure 'Number of Customers' = COUNT('Databel - Data'[Customer ID])
		formatString: 0
		lineageTag: f9d5c9e4-dad1-4cef-9376-c8116b2e6888

	measure 'Number of Unique Customers' = DISTINCTCOUNT('Databel - Data'[Customer ID])
		formatString: 0
		lineageTag: 08316ad6-279f-45fc-8eb9-2273868882f7

	measure 'Number of Churned Customers' = SUM('Databel - Data'[Churned])
		formatString: 0
		lineageTag: 0be4671c-c5b5-4f1e-8ef7-6475ef6cf617

	measure 'Churn Rate' = [Number of Churned Customers] / [Number of Customers]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 400fb96a-9a36-4c9e-96f6-9d9c3502afe9

	measure 'Avg Customer Service Calls' = AVERAGE('Databel - Data'[Customer Service Calls])
		lineageTag: ebd65644-f2b6-4be6-b9d0-3abd2678e81a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Extra International Charges' = SUM('Databel - Data'[Extra International Charges]) / [Number of Customers]
		lineageTag: fdda9aaf-7dd5-43ec-93b9-7ce40582cbed

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Extra Data Charges' = SUM('Databel - Data'[Extra Data Charges]) / [Number of Customers]
		lineageTag: 1d134528-a3e7-410d-9bd1-b600c53e6f3a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Customer ID'
		dataType: string
		lineageTag: 1f33d818-44db-42a9-84b9-a8f20d7f32e2
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Churn Label'
		dataType: string
		lineageTag: 00438ea6-1c65-4f6a-972e-8cd51db1987c
		summarizeBy: none
		sourceColumn: Churn Label

		annotation SummarizationSetBy = Automatic

	column 'Account Length (in months)'
		dataType: int64
		formatString: 0
		lineageTag: 7c88e68d-c8e1-478c-a2fb-4f4dd0b395e8
		summarizeBy: sum
		sourceColumn: Account Length (in months)

		annotation SummarizationSetBy = Automatic

	column 'Local Calls'
		dataType: int64
		formatString: 0
		lineageTag: f85bbd9d-ebfe-451c-ae02-42ce1d23eec2
		summarizeBy: sum
		sourceColumn: Local Calls

		annotation SummarizationSetBy = Automatic

	column 'Local Mins'
		dataType: double
		lineageTag: 7e70ef46-e25b-4a8d-8a0f-ff944d2b2f37
		summarizeBy: sum
		sourceColumn: Local Mins

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Intl Calls'
		dataType: int64
		formatString: 0
		lineageTag: 157b1fe2-58c6-4658-9f0f-22aac315e456
		summarizeBy: sum
		sourceColumn: Intl Calls

		annotation SummarizationSetBy = Automatic

	column 'Intl Mins'
		dataType: double
		lineageTag: ee5e9f0e-5671-4eeb-9779-ae36d16e3323
		summarizeBy: sum
		sourceColumn: Intl Mins

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Intl Active'
		dataType: string
		lineageTag: d0d38f77-1b8f-4ad3-aaf4-567ee11c25b8
		summarizeBy: none
		sourceColumn: Intl Active

		annotation SummarizationSetBy = Automatic

	column 'Intl Plan'
		dataType: string
		lineageTag: 4ec91560-9eb9-4faa-bb9a-2cc5d3c35c3b
		summarizeBy: none
		sourceColumn: Intl Plan

		annotation SummarizationSetBy = Automatic

	column 'Extra International Charges'
		dataType: int64
		formatString: 0
		lineageTag: 3e10183b-1405-4915-8a7b-a350f9fb7ff4
		summarizeBy: sum
		sourceColumn: Extra International Charges

		annotation SummarizationSetBy = Automatic

	column 'Customer Service Calls'
		dataType: int64
		formatString: 0
		lineageTag: aa1845c4-0729-4613-9ebf-e640e43ceb55
		summarizeBy: sum
		sourceColumn: Customer Service Calls

		annotation SummarizationSetBy = Automatic

	column 'Avg Monthly GB Download'
		dataType: int64
		formatString: 0
		lineageTag: ffb77da1-155f-45f2-9771-fb52de25af6d
		summarizeBy: sum
		sourceColumn: Avg Monthly GB Download

		annotation SummarizationSetBy = Automatic

	column 'Unlimited Data Plan'
		dataType: string
		lineageTag: bb3dd428-5f6c-41d0-8d55-b0c1c9b902b8
		summarizeBy: none
		sourceColumn: Unlimited Data Plan

		annotation SummarizationSetBy = Automatic

	column 'Extra Data Charges'
		dataType: int64
		formatString: 0
		lineageTag: e263b4d7-6fdf-429d-a574-5061b9a14b6a
		summarizeBy: sum
		sourceColumn: Extra Data Charges

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 084ef702-f9d2-4aff-a120-b578446b1ddc
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Phone Number'
		dataType: string
		lineageTag: 845949dc-9fb3-48cb-9a08-bc6bad4a9a5a
		summarizeBy: none
		sourceColumn: Phone Number

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 717237cc-ac0b-4e5c-8904-bce3a0a9dd9a
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		lineageTag: 32d634c1-ba79-4304-b726-01a6358ab29d
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Databel - Data","TableItemName":"Age (bins)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column 'Under 30'
		dataType: string
		lineageTag: 652ef4e7-853d-4f76-a499-01e89b456178
		summarizeBy: none
		sourceColumn: Under 30

		annotation SummarizationSetBy = Automatic

	column Senior
		dataType: string
		lineageTag: 36a77841-84e2-44df-9812-e79003f39683
		summarizeBy: none
		sourceColumn: Senior

		annotation SummarizationSetBy = Automatic

	column Group
		dataType: string
		lineageTag: 1a0c110c-807b-4d5f-ab6e-be0024777724
		summarizeBy: none
		sourceColumn: Group

		annotation SummarizationSetBy = Automatic

	column 'Number of Customers in Group'
		dataType: int64
		formatString: 0
		lineageTag: 8f940ec6-c45b-47e0-8d4f-8a7e7d9f8e7c
		summarizeBy: sum
		sourceColumn: Number of Customers in Group

		annotation SummarizationSetBy = Automatic

	column 'Device Protection & Online Backup'
		dataType: string
		lineageTag: 56e8e7a2-20a4-4996-a9be-90050df5cbb0
		summarizeBy: none
		sourceColumn: Device Protection & Online Backup

		annotation SummarizationSetBy = Automatic

	column 'Contract Type'
		dataType: string
		lineageTag: d939c6b6-42bc-484f-9625-092943247f3a
		summarizeBy: none
		sourceColumn: Contract Type

		annotation SummarizationSetBy = Automatic

	column 'Payment Method'
		dataType: string
		lineageTag: 50a8871e-5366-40ac-85e5-d1a85a897399
		summarizeBy: none
		sourceColumn: Payment Method

		annotation SummarizationSetBy = Automatic

	column 'Monthly Charge'
		dataType: int64
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 82c5988b-10af-487e-bc0d-61383a843c50
		summarizeBy: sum
		sourceColumn: Monthly Charge

		annotation SummarizationSetBy = Automatic

	column 'Total Charges'
		dataType: int64
		formatString: 0
		lineageTag: 1f42b0ac-6110-49da-ae91-6031a4fc1506
		summarizeBy: sum
		sourceColumn: Total Charges

		annotation SummarizationSetBy = Automatic

	column 'Churn Category'
		dataType: string
		lineageTag: a97777f4-d6c7-444e-a60b-0b696ac6943c
		summarizeBy: none
		sourceColumn: Churn Category

		annotation SummarizationSetBy = Automatic

	column 'Churn Reason'
		dataType: string
		lineageTag: 12fb86fc-4528-4b4d-a480-5bae25b9c7d9
		summarizeBy: none
		sourceColumn: Churn Reason

		annotation SummarizationSetBy = Automatic

	column Churned = IF('Databel - Data'[Churn Label] = "Yes", 1, 0)
		formatString: 0
		lineageTag: bb144993-ded0-4947-8a0a-26314f018cf0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Demographics = IF('Databel - Data'[Under 30]="Yes", "Under 30", IF('Databel - Data'[Senior] = "Yes", "Senior", "Other") )
		lineageTag: dae09c43-fe57-4c01-bac8-bdd12b899028
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Age (bins)' =
			IF(
				ISBLANK('Databel - Data'[Age]),
				BLANK(),
				INT('Databel - Data'[Age] / 5) * 5
			)
		formatString: 0
		lineageTag: 6e2a55ff-c136-4ff0-9ea2-4e67738a1a2d
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Databel - Data"
				          }
				        },
				        "Property": "Age"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 5.0,
				      "unit": 0
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"d","Entity":"Databel - Data"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"d"}},"Property":"Age"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"d"}},"Property":"Age"}},"Size":5.0}}}}

		annotation SummarizationSetBy = Automatic

	column 'Contract Category' = SWITCH('Databel - Data'[Contract Type], "One Year", "Yearly", "Two Year", "Yearly", "Month-to-Month", "Monthly", "erro")
		lineageTag: 667cd078-b019-46d4-b4d8-5fab0c3f45d1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Grouped Consumption' = IF('Databel - Data'[Avg Monthly GB Download] < 5, "Less than 5 GB", IF('Databel - Data'[Avg Monthly GB Download] < 10, "Between 5 and 10 GB", "10 or more GB"))
		lineageTag: 27d22510-b5cf-4014-8540-7b3379156e64
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Databel - Data-b37c2b98-7492-4a48-8b7a-5332ca70065a' = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://assets.datacamp.com/production/repositories/5993/datasets/d6a32ec1293e10bd44441b4f8b4fe60b9776e0d1/Databel%20-%20Data.csv"),[Delimiter=",", Columns=29, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Customer ID", type text}, {"Churn Label", type text}, {"Account Length (in months)", Int64.Type}, {"Local Calls", Int64.Type}, {"Local Mins", type number}, {"Intl Calls", Int64.Type}, {"Intl Mins", type number}, {"Intl Active", type text}, {"Intl Plan", type text}, {"Extra International Charges", Int64.Type}, {"Customer Service Calls", Int64.Type}, {"Avg Monthly GB Download", Int64.Type}, {"Unlimited Data Plan", type text}, {"Extra Data Charges", Int64.Type}, {"State", type text}, {"Phone Number", type text}, {"Gender", type text}, {"Age", Int64.Type}, {"Under 30", type text}, {"Senior", type text}, {"Group", type text}, {"Number of Customers in Group", Int64.Type}, {"Device Protection & Online Backup", type text}, {"Contract Type", type text}, {"Payment Method", type text}, {"Monthly Charge", Int64.Type}, {"Total Charges", Int64.Type}, {"Churn Category", type text}, {"Churn Reason", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

